#*****************************************************************************
#  * Copyright (c) 2022 Intecs.
#  *
#  *    
#  * All rights reserved. This program and the accompanying materials
#  * are made available under the terms of the Eclipse Public License v2.0
#  * which accompanies this distribution, and is available at
#  * http://www.eclipse.org/legal/epl-v20.html
#  *
#  * Contributors:
#  *  Felicien Ihirwe
#  *
#  *****************************************************************************/

version: "3.9"
services:
  MQTTBroker:
    image: eclipse-mosquitto
    hostname: FogMachine
    container_name: MQTTBroker
    ports:
      - 1883:1883 /tcp
      - 9001:9001 /udp
    volumes:
      - ./conf:/mosquitto/conf
      - ./data:/mosquitto/data
      - ./log:/mosquitto/log
    networks:
      - MQTTBroker_net
  
networks:
  MQTTBroker_net:
    driver: bridge
